- software/script/chameleon_cli_main.py
Changed the exit message from "Bye, thanks for you.  ^.^ " to "Bye, thank you.  ^.^ ", which is a neater message.
> Fixed spelling on exit message

- firmware/application/src/sdk_config.h
Fixed the USB descriptor typo from Porxgrind to Proxgrind
Im a typo developer ;)
> Fixed Porxgrind typo

- firmware/application/Makefile
Currently, repo does not compile anymore for gcc 10
Fix to introduce some cflags only on gcc versions >= 12
> Fix cflags for gcc < 12

- .github/workflows/firmware.yml
- firmware/build.sh
Two DFU packages are generated per target:
- `$target-dfu-app.zip`: only application is flashed
- `$target-dfu-full.zip`: bootloader, softdevice and application are flashed
> Generate DFU packages in CI

- firmware/application/src/rfid/nfctag/lf/lf_tag_em.c
Some IDs are not emulated properly and are not detected properly e.g. with a Proxmark.
This patch removes the `m_is_send_reboardcast_last_edge` hack and the call to `ANT_NO_MOD` when checking the field presence.
> fix LF EM emulation

- software/script/chameleon_cli_unit.py
- software/script/chameleon_cmd.py
- software/script/chameleon_com.py
Add flag to cmd to tell to close connection nicely after having sent the cmd.
Useful e.g. for closing comm after sending `hw dfu`
> client: don't let recv thread crashing after hw dfu

- firmware/application/src/app_cmd.c
- firmware/application/src/data_cmd.h
- firmware/build.sh
- software/script/chameleon_cli_main.py
- software/script/chameleon_cli_unit.py
- software/script/chameleon_cmd.py
This commit :
- create a new simple command in firmware and Python client : `DATA_CMD_GET_DEVICE_ADDRESS`
- expose an existing one: `DATA_CMD_GET_DEVICE_CHIP_ID`
- modify `build.sh` to generate DFU package without `bootloader_merged.hex`, `mergehex` is only used one time.
> Clean nrf* part of build.sh + get device address & chip id

- .github/workflows/firmware.yml
GitHub doesn't allow unauthorized users to download artifacts from actions. This PR will allow GitHub Actions to publish releases (pre-release) with .zip files for DFU (so users can flash it without GitHub account)
Required for https://github.com/GameTec-live/ChameleonUltraGUI/pull/52
> Upload DFU zip files to releases

- .gitignore
- firmware/application/Makefile
- firmware/application/src/app_cmd.c
- firmware/application/src/app_main.c
- firmware/application/src/data_cmd.h
- firmware/application/src/rfid/nfctag/tag_emulation.c
- firmware/application/src/rfid/nfctag/tag_emulation.h
- firmware/application/src/rfid/nfctag/tag_persistence.c
- firmware/application/src/rfid/nfctag/tag_persistence.h
- firmware/application/src/settings.c
- firmware/application/src/settings.h
- firmware/application/src/utils/fds_ids.h
- firmware/common/utils.h
- software/script/chameleon_cli_main.py
- software/script/chameleon_cli_unit.py
- software/script/chameleon_cmd.py
- software/script/chameleon_status.py
This change adds animation change support + ability to control it from CLI.
By default it uses full animation mode (as stock firmware) but it allows user to disable wake-up and sleep animations completely (mode 2) or use minimal animation (mode 1).
The reason for making this change is that waiting even for this single cycle of led swipe when triggered by reader makes it hard to use with some readers. Moreover, having such long animations is, to say the least, frustrating. 
Reason of having mode 1 is that when there is no animation at all when you wake Chameleon with button press, button up is registered as command to change slot, so slight delay helps alleviate that problem. In this mode there is no sleep swipe nor rf field wake-up animation. 
In both mode 1 and 2 there are animations for …
> Add animation modes support

- firmware/application/src/app_cmd.c
Fixed block_count calculation in cmd_processor_set_mf1_emulator_block.
Changed loop boundary to length. Although it does not affect behavior, it is confusing to have length - 1 as a boundary because we want to parse data elements from 1 to length - 1 including.
> Fix data sanity check

- .github/workflows/firmware.yml
Fix workflow using deprecated stuff.
For an example release see [here](https://github.com/augustozanellato/ChameleonUltra/releases/tag/dev)
> Use single release for dev builds

- firmware/application/src/app_cmd.c
- firmware/application/src/data_cmd.h
- firmware/application/src/rfid/nfctag/hf/nfc_mf1.c
- firmware/application/src/rfid/nfctag/hf/nfc_mf1.h
- firmware/nrf52_sdk/components/toolchain/gcc/Makefile.posix
- software/script/chameleon_cli_main.py
- software/script/chameleon_cli_unit.py
- software/script/chameleon_cmd.py
- software/script/chameleon_com.py
- software/script/chameleon_cstruct.py
- software/script/chameleon_status.py
User changes:
`hw slot info` renamed to `hw slot list` and support fetching nicknames and current Mifare Classic emulator settings. Also will show disabled slots
Implemented `hf mf settings` to set gen1/gen2/anti-coll/write mode, check --help for mode details
Code changes:
Code quality improvements, typo fixes, spaces. Adapt client to python style. 
`nfc_tag_mf1_random_nonce` will now provide more randomness on nested authorization, gives us ability to recover keys via Hardnested attack
Exposed methods to set/get emulator settings
Implemented gen2 mode (write to block 0)
Won't conflict with https://github.com/RfidResearchGroup/ChameleonUltra/pull/56, but will with https://github.com/RfidResearchGroup/ChameleonUltra/pull/66
> Implement new Mifare Classic emulator configuration commands

- software/script/chameleon_cli_main.py
This adds persistent command history to the CLI, which is stored in `~/.chameleon_history` (should resolve properly on all platforms)
> Store CLI history in ~/.chameleon_history

- firmware/build.sh
- firmware/flash-dfu-app.sh
- firmware/flash-dfu-full.sh
Fixes `Overlapping segments detected at address 1040384.ERROR: The hex files cannot be merged since there are conflicts.`
Was caused by `build.sh` overwriting `application.hex` with a version merged with bootloader settings, wasn't catched during testing because only clean builds were tested.
Fix involves using a temp directory for storing the binaries that will be put into `type-binaries.zip` so that the merged application can be renamed to `application.hex` without breaking successive builds.
`flash-dfu-*.sh` scripts have also been fixed to account for the new file names and to properly enter dfu even if script is ran from repo root (for example `firmware/flash-dfu-app.sh`)
> Fix stuff I broke yesterday

- software/script/chameleon_cli_unit.py
Avoid
```
Chameleon Connect fail: [Errno 2] could not open port /dev/ttyS15
/dev/ttyS39: [Errno 2] No such file or directory: '/dev/ttyS15\r\n/dev/ttyS39'
```
By only returning the first COM port with `VID_6868&PID_8686`
> Fix multiple Chameleon connected on WSL1

- CHANGELOG.md
- firmware/application/src/app_cmd.c
When I use the `DATA_CMD_GET_DEVICE_ADDRESS` cmd, I find the response is different with the address displayed from Android CU GUI.
So I found the `FICR->DEVICEADDR` is random addr, need to convert to static addr.
> Fix device address is not the same with APP

- CHANGELOG.md
- software/script/chameleon_utils.py
This fixes the autocomplete bug that would insert additional hyphens after tab-completing arguments.
Closes #97
> Fix argument autocompleter bug (#97)

- software/script/chameleon_cli_main.py
This fixes a bug where after a KeyboardInterrupt the application would crash since it would try to split a string that does not exist.
> Fix a bug in multiline command implementation

- firmware/application/src/rfid/nfctag/hf/nfc_14a.c
- firmware/application/src/rfid/nfctag/hf/nfc_mf1.h
After nearly a week of testing and attempted repairs, MFC simulation is now compatible with most OEM readers and has solved the compatibility issues with mobile phones caused by fixing OEM compatibility issues. Note that this change temporarily disable FAST_SIM, this may not be the final fix we want. In theory, we should focus on FAST_SIM functionality is controllable, rather than simply disable.
The fixed of this big bug cannot do without the help of the community. Thanks to @doegox and @spp2000, as well as to many others in the community for their help.
Based on feedback from the current community, this fix can make their OEM card readers work perfectly. If you encounter issues that cannot work on OEM card readers, please try update to this firmware. And after the test, please feedback …
> Mfc 1k Full emulation (not UID only) with OEM readers bugs fixed.

- software/script/chameleon_cmd.py
When use the "hf mf eread" command via CLI it crashes as bytearray() do not likes the params
> Solved bug that makes hf mf eread command crashes

- docs/technical_whitepaper.md
Simulation and emulation used within same document while having no distinctive technical differentiating usage, propose changing all instances to Emulate/Emulation
> Update nomenclature technical_whitepaper.md

- CHANGELOG.md
- firmware/application/src/utils/fds_util.c
fds_util event handler was ignoring all the events related to peer_manager files and that was causing a deadlock while waiting for record deletion that in turn caused a wdt reset, usually this resulted in a partially done factory reset.
The fix adds a `ignore_pm` flag to op_info struct that gets cleared by fds_wipe allowing for a true reset to happen.
> Fix factory reset hang/wdt reset

- CHANGELOG.md
- docs/protocol.md
- firmware/application/src/app_cmd.c
- firmware/application/src/data_cmd.h
- firmware/application/src/rfid/reader/hf/rc522.c
- firmware/application/src/rfid/reader/hf/rc522.h
- software/script/chameleon_cli_unit.py
- software/script/chameleon_cmd.py
- software/script/chameleon_enum.py
Added support for mifare classic value block operations
> Added support for mifare classic value block operations

- CHANGELOG.md
- software/script/chameleon_cli_unit.py
This PR will run as many `mfkey32v2` processes in parallel than the host CPUs count. It makes the `hf mf elog --decrypt` command much faster.
> CLI: parallelize mfkey32v2 processes

- CHANGELOG.md
- software/script/chameleon_cli_unit.py
This (often largely) improves the speed of the decrypt process. On my laptop, with the same logs (37 records for one block and 37 records for another block), here are the performances, as measuerd using a simple command:
```bash
time echo -e "hw connect\nhf mf elog --decrypt\nhw disconnect" | ./chameleon_cli_main.py
```
- Before parallelisation (#187): 14m59,277s
- With parallelisation (current main): 6m13,513s
- With item skipping (this PR): 2m42,491s
> CLI: skip already used items in `hf mf elog --decrypt`

- CHANGELOG.md
- software/script/chameleon_cli_unit.py
In the nested attack of the cli the target key type parameter (`--ta` / `--tb`) is not used.
This PR sets the `type_target` based on the target key type parameter instead of the known key type parameter.
> cli: fix unused target key type parameter for nested

- software/script/chameleon_cli_unit.py
I noticed that when running the CLI with python 3.9, the `type_target` enum would be converted to a string representation of the enum, instead to its numerical value, i.e., `MfcKeyType.A` instead of `96`. This caused the execution of the nested binary to fail.
> cli: Fix cmd_parameter generation for nested for python 3.9

- software/script/chameleon_cli_unit.py
- software/script/chameleon_utils.py
**Thanks** to @taichunmin and @rickNmorty2 for the implementation and the enhancement of `fchk` and `dump` commands. 
Add `print_mem_dump(bindata, blocksize)` in `chameleon_util.py` to display memory content
Add `hf mf eview` to display emulation memory content
```
[USB] chameleon --> hf mf eview -s 1
[=] ----+-------------------------------------------------+-----------------
[=] blk | data                                            | ascii
[=] ----+-------------------------------------------------+-----------------
[=]   1 | C7 CF 0C 03 07 08 04 00 62 63 64 65 66 67 68 69 | ........bcdefghi 
[=]   2 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]   3 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]   4 | 00 00 00 00 00 00 FF 07 80 69 FF …
```
> Add CLI view commands to display memory content 

- firmware/application/src/rfid/nfctag/lf/lf_tag_em.c
- firmware/application/src/rfid/nfctag/lf/lf_tag_em.h
The original EM4100 tag continuously sends its ID.
The root problem, in my point of view, was that CU started to "feel" the field too far to be able to modulate it deep enough,
and 3 times (LF_125KHZ_BROADCAST_MAX) of repeating takes only about 100ms, CU is still not close enough to the reader.
That is why the emulation worked only if the CU moved past the reader quickly (fly by).
> fix-LF-emulation

- firmware/application/src/app_cmd.c
- firmware/application/src/app_main.c
- firmware/application/src/rfid_main.c
- firmware/application/src/rfid_main.h
Previously, using `hw slot change -s N` via the CLI would cause inconsistent LED colors:
- The LED for the newly selected slot turned on, but old slot LEDs remained lit.
- LED colors did not reflect the actual slot configuration (e.g., slot 3 LED showed red instead of blue).
Changes:
- Used `get_color_by_slot()` to determine correct color per slot based on enabled tag types.
- Modified `get_color_by_slot()` to also check if LF/HF sensing is enabled.
Switching slots via CLI now behaves consistently with button-based slot changes.
Closes #160
> Fix incorrect slot LED indication when switching via CLI

- software/script/chameleon_cli_unit.py
- software/script/chameleon_cmd.py
- software/script/chameleon_utils.py
- software/script/tests/test_hard_acquire.py
After the last few changes (#263, #267), the minimum Python version required to run the Chameleon CLI effectively became **3.11**, due to the use of:
* The Python 3.10+ type hint syntax `int | None`
* `int.from_bytes()` calls without the required `byteorder` argument (mandatory in < 3.11)
However, the CLI documentation still states Python 3.9 as the minimum supported version.
This PR restores compatibility with Python 3.9 by:
* Replacing `int | None` with `Union[int, None]` for type hints.
* Adding an explicit `byteorder='big'` argument to all `int.from_bytes()` calls.
This way, the documented Python 3.9 requirement remains accurate.
Alternatively, if Python 3.11+ is intended to be the new baseline, the documentation should be updated accordingly — but I suggest keeping compatibility …
> Restore Python 3.9 compatibility for Chameleon CLI

- CHANGELOG.md
- firmware/application/src/app_cmd.c
- firmware/application/src/rfid/reader/hf/mf1_toolbox.c
When I implement the MF1_CHECK_KEYS_ON_BLOCK command in my JavaScript SDK, the error response for the command is incorrect.
/cc @Foxushka
> fix error response of cmd MF1_CHECK_KEYS_ON_BLOCK

- firmware/application/Makefile
- firmware/application/src/app_cmd.c
- firmware/application/src/app_main.c
- firmware/application/src/data_cmd.h
- firmware/application/src/rfid/nfctag/lf/lf_tag_em.c
- firmware/application/src/rfid/nfctag/lf/lf_tag_em.h
- firmware/application/src/rfid/nfctag/lf/protocols/t55xx.h
- firmware/application/src/rfid/nfctag/lf/protocols/viking.c
- firmware/application/src/rfid/nfctag/lf/protocols/viking.h
- firmware/application/src/rfid/nfctag/tag_base_type.h
- firmware/application/src/rfid/nfctag/tag_emulation.c
- firmware/application/src/rfid/reader/lf/lf_reader_data.h
- firmware/application/src/rfid/reader/lf/lf_reader_main.c
- firmware/application/src/rfid/reader/lf/lf_reader_main.h
- firmware/application/src/rfid/reader/lf/lf_viking_data.c
- software/script/chameleon_cli_unit.py
- software/script/chameleon_cmd.py
- software/script/chameleon_enum.py
This PR adds support for the Viking protocol, which is a low-frequency protocol (RF/32 with Manchester encoding, 2 data blocks : 64-bit data). The card ID is an 8-digit hexadecimal number.
Place a T5577 against CU then run the following commands...
lf viking write --id 11223344
lf viking read
Next try emulation...
hw slot type -t Viking -s 4
hw slot enable -s 4 --lf
lf viking econfig --slot 4 --id 13371337
hw slot store
hw slot list
Notice the slot 4 will show the information. Select slot 4 and read with Viking reader (or Flipper Zero).
Try cloning a card using, Long press A while holding a Viking card (or programmed T5577) against CU & notice all LEDs blink green. If not, try Long press A again. Read CU emulation with a Viking reader (or Flipper Zero).
hw slot list should now show a …
> Add LF Viking support
