software/script/requirements.txt

Having a requirements.txt is never a bad idea, especially if the project isnt covered by the default libraries (eg: colorama, pyserial)
Its also recommended to keep this file up to date with all used libraries and having a recent ish version of the libraries used.
If theres something missing or the versions (somehow) arent fine, please, edit the file...

Added requirements.txt

---

firmware/application/src/app_main.c

Changed the Comment language to English for better readability

Comment language

---

software/.gitignore
software/script/chameleon_cli_unit.py

Added compatabilty with linux / unix by just adding a if and changing the filenames accordingly (nested, darkside)
and i translated some chineese in the gitignore

Added Linux / Unix Compatabilty

---

How_to_use_Firmware.md
firmware/application/src/app_main.c

Translation + Compiling instructions

---

firmware/application/src/rfid/nfctag/lf/lf_tag_em.c
firmware/nrf52_sdk/components/toolchain/gcc/Makefile.common
firmware/nrf52_sdk/integration/nrfx/nrfx_config.h
software/.gitignore
software/script/chameleon_cli_unit.py

when reenable lf timer, only half edge is sent, which causes the PM3 failes to get the correct start bit.

[Fix] LF send edge issue

---

software/script/chameleon_cli_main.py
software/script/chameleon_cli_unit.py
software/script/chameleon_com.py

Minor changes to python client to avoid errors on exit and to allow exit with ctrl-d (like pm3 client)

Graceful exit, also on ctrl-d

---

software/script/chameleon_cli_unit.py

switch autoconnect over to vid due to MS description and name implementation
Sooo, heres the fix for my untested autoconnect implementation... The previous didnt work due to MS not exposing the devices description but instead showing generic info because its a com port. Im sorry, i tested it with my lite, it should work...

fix autoconnect

---

firmware/application/src/rfid/nfctag/lf/lf_tag_em.c

make sure to sample the field only during the last no-mod half bit of a series of ID broadcasts

LF EM: sample field only when mod is off

---

firmware/application/src/rfid/nfctag/hf/nfc_ntag.c

repo is currently broken, this fixes it.

fix compilation

---

firmware/Dockerfile
firmware/Makefile.defs
firmware/application/Makefile
firmware/application/src/app_cmd.c
firmware/application/src/data_cmd.h
software/script/chameleon_cli_main.py
software/script/chameleon_cli_unit.py
software/script/chameleon_cmd.py

I think it would be useful to have hash of latest git commit
I do not own chameleon ultra yet, so I did not have a chance to test it yet

Add git version command

---

firmware/application/Makefile
firmware/application/src/app_cmd.c
firmware/application/src/data_cmd.h
firmware/application/src/utils/delayed_reset.c
firmware/application/src/utils/delayed_reset.h
firmware/application/src/utils/fds_util.c
firmware/application/src/utils/fds_util.h
software/script/chameleon_cli_main.py
software/script/chameleon_cli_unit.py
software/script/chameleon_cmd.py

It's implemented as deleting all the FDS records present in flash, this way it won't need to be touched when new FDS records are introduced.
It's suggested to run it once because commit 997f58d0d0a6d12861eeae0150a3f7f03ba8eddb left some unused records around in the flash.

Add factory reset command

---

firmware/application/src/app_main.c

Offline clone of LF UID

---

firmware/application/src/app_main.c
firmware/application/src/rfid_main.c

Offline read status notification with LEDs

---

.editorconfig

Editorconfig would mean a lot to me to sync style in my editor to what you have here

Editorconfig for py, c, h

---

software/script/chameleon_cli_unit.py

Add port auto detection on WSL1

---

docs/README.md
docs/sdk.md

I added a page for SDKs and my SDK.

Docs: Add sdk.md

---

.github/workflows/build_client.yml
CHANGELOG.md
software/.gitignore
software/pyinstaller.spec
software/script/chameleon_cli_unit.py
software/src/mfkey.c

Allows for standalone cli binaries to be built for releases and PRs

Add client PyInstaller support

---

docs/cli.md
software/script/chameleon_cli_unit.py

Add the linux docs for arch and ubuntu, took long enough ;)

doc: finally add linux

---

CHANGELOG.md
docs/protocol.md
firmware/Makefile.defs

Change git version from `dev-5-g74f4eb8` to `v2.0.0-101-g74f4eb8`

Change git version to version tag instead of dev tag.

---

.github/workflows/build_client.yml

Try to fix the issue of workflow terminating due to pyinstaller installation failure.

Specify the Python version used by workflow as 3.12

---

software/script/chameleon_cli_unit.py

Also fix when the dir conatains hardnested is read only, see #261

Use execute_tool to simplify running hardnested tool
